/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register/buyer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Buyer */
        post: operations["register_buyer_api_v1_auth_register_buyer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/seller": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Seller */
        post: operations["register_seller_api_v1_auth_register_seller_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Access Token */
        post: operations["refresh_access_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revokes a refresh token on demand (e.g. user-initiated sign-out on
         *     a device) rather than waiting for it to either be rotated via
         *     `/auth/refresh` or expire naturally. Silently succeeds for an
         *     already-invalid/expired token — logging out doesn't need to prove the
         *     token was ever valid.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_v1_products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_api_v1_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Products */
        get: operations["list_my_products_api_v1_products_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_v1_products__product_id__get"];
        put?: never;
        post?: never;
        /** Deactivate Product */
        delete: operations["deactivate_product_api_v1_products__product_id__delete"];
        options?: never;
        head?: never;
        /** Update Product */
        patch: operations["update_product_api_v1_products__product_id__patch"];
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_v1_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_api_v1_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_api_v1_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Order Transactions */
        get: operations["list_order_transactions_api_v1_orders__order_id__transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Order Status */
        patch: operations["update_order_status_api_v1_orders__order_id__status_patch"];
        trace?: never;
    };
    "/api/v1/orders/{order_id}/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Return
         * @description Self-service return: within the policy window and in good
         *     condition, this auto-approves a full refund with no seller
         *     counter-evidence step — distinct from `POST /disputes`, which is for
         *     contested claims where both sides submit evidence. A damaged/
         *     incomplete-condition return still creates a dispute, but an open one
         *     the seller can respond to, since "the buyer says it's damaged" alone
         *     isn't grounds for an unconditional refund the way "I don't want it
         *     anymore, still sealed, day 3 of 7" is.
         */
        post: operations["request_return_api_v1_orders__order_id__return_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fraud/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fraud Alerts */
        get: operations["list_fraud_alerts_api_v1_fraud_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fraud/logs/{fraud_log_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Review Fraud Log */
        patch: operations["review_fraud_log_api_v1_fraud_logs__fraud_log_id__review_patch"];
        trace?: never;
    };
    "/api/v1/trust/sellers/{seller_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Trust Score */
        get: operations["get_current_trust_score_api_v1_trust_sellers__seller_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trust/sellers/{seller_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trust Score History */
        get: operations["get_trust_score_history_api_v1_trust_sellers__seller_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trust/sellers/{seller_id}/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Recompute */
        post: operations["trigger_recompute_api_v1_trust_sellers__seller_id__recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trust/sellers/{seller_id}/onchain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Onchain Trust
         * @description Reads the score straight from TrustScore.sol (the simpler
         *     event-delta model), separate from the multi-factor score above —
         *     the two are different models by design, see backend/README.md.
         */
        get: operations["get_onchain_trust_api_v1_trust_sellers__seller_id__onchain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Review */
        post: operations["create_review_api_v1_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/sellers/{seller_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seller Reviews */
        get: operations["list_seller_reviews_api_v1_reviews_sellers__seller_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recommendations */
        get: operations["list_recommendations_api_v1_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{recommendation_id}/click": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Click */
        post: operations["record_click_api_v1_recommendations__recommendation_id__click_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/ctr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ctr Report */
        get: operations["ctr_report_api_v1_recommendations_ctr_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disputes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Disputes */
        get: operations["list_disputes_api_v1_disputes_get"];
        put?: never;
        /** Raise Dispute */
        post: operations["raise_dispute_api_v1_disputes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disputes/{dispute_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Evidence */
        post: operations["submit_evidence_api_v1_disputes__dispute_id__evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disputes/{dispute_id}/arbitrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Arbitrate Dispute */
        patch: operations["arbitrate_dispute_api_v1_disputes__dispute_id__arbitrate_patch"];
        trace?: never;
    };
    "/api/v1/disputes/{dispute_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dispute */
        get: operations["get_dispute_api_v1_disputes__dispute_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Wishlist */
        get: operations["list_wishlist_api_v1_wishlist_get"];
        put?: never;
        /** Add To Wishlist */
        post: operations["add_to_wishlist_api_v1_wishlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlist/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove From Wishlist */
        delete: operations["remove_from_wishlist_api_v1_wishlist__product_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User Status */
        patch: operations["update_user_status_api_v1_admin_users__user_id__status_patch"];
        trace?: never;
    };
    "/api/v1/admin/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics */
        get: operations["analytics_api_v1_admin_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/blockchain-hashes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Blockchain Hashes */
        get: operations["list_blockchain_hashes_api_v1_admin_blockchain_hashes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminUserRead */
        AdminUserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /** Is Verified */
            is_verified: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at: string | null;
            /** Seller Id */
            seller_id?: string | null;
            /** Buyer Id */
            buyer_id?: string | null;
        };
        /** AnalyticsReport */
        AnalyticsReport: {
            /** Total Users */
            total_users: number;
            /** Total Buyers */
            total_buyers: number;
            /** Total Sellers */
            total_sellers: number;
            /** Total Admins */
            total_admins: number;
            /** Total Products */
            total_products: number;
            /** Active Products */
            active_products: number;
            /** Total Orders */
            total_orders: number;
            /** Orders By Status */
            orders_by_status: {
                [key: string]: number;
            };
            /** Total Transactions */
            total_transactions: number;
            /** Total Revenue */
            total_revenue: string;
            /** Fraud Flagged Transactions */
            fraud_flagged_transactions: number;
            /** Fraud Flag Rate */
            fraud_flag_rate: number;
            /** Average Seller Trust Score */
            average_seller_trust_score: number;
            /** Open Disputes */
            open_disputes: number;
            /** Total Disputes */
            total_disputes: number;
        };
        /** BlockchainHashRead */
        BlockchainHashRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Entity Type */
            entity_type: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Tx Hash */
            tx_hash: string;
            /** Block Number */
            block_number: number | null;
            /** Network */
            network: string;
            /** Event Type */
            event_type: string;
            /** Payload Hash */
            payload_hash: string | null;
            /** Confirmed At */
            confirmed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BuyerProfileRead */
        BuyerProfileRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Wallet Address */
            wallet_address: string | null;
            /** Price Sensitivity */
            price_sensitivity: string;
            /** Preferred Categories */
            preferred_categories: string[];
            /** City */
            city: string | null;
            /** Account Age Days */
            account_age_days: number;
            /** Is Onchain Registered */
            is_onchain_registered: boolean;
        };
        /** BuyerRegisterRequest */
        BuyerRegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone?: string | null;
            /** Preferred Categories */
            preferred_categories?: string[];
            /** City */
            city?: string | null;
        };
        /** CTRReport */
        CTRReport: {
            /** Algorithm */
            algorithm: string | null;
            /** Impressions */
            impressions: number;
            /** Clicks */
            clicks: number;
            /** Purchases */
            purchases: number;
            /** Ctr */
            ctr: number;
            /** Click To Purchase Rate */
            click_to_purchase_rate: number;
        };
        /** DisputeArbitrate */
        DisputeArbitrate: {
            /** Seller Share Bps */
            seller_share_bps: number;
        };
        /** DisputeCreate */
        DisputeCreate: {
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            reason: components["schemas"]["DisputeReason"];
            /** Description */
            description?: string | null;
            /**
             * Evidence Score
             * @default 0
             */
            evidence_score: number | string;
        };
        /** DisputeEvidenceSubmit */
        DisputeEvidenceSubmit: {
            /** Evidence Score */
            evidence_score: number | string;
        };
        /** DisputeRead */
        DisputeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /**
             * Raised By User Id
             * Format: uuid
             */
            raised_by_user_id: string;
            reason: components["schemas"]["DisputeReason"];
            /** Description */
            description: string | null;
            /** Evidence Buyer Score */
            evidence_buyer_score: string | null;
            /** Evidence Seller Score */
            evidence_seller_score: string | null;
            status: components["schemas"]["DisputeStatus"];
            /** Resolution Outcome */
            resolution_outcome: string | null;
            /** Seller Share Bps */
            seller_share_bps: number | null;
            /** Resolved By */
            resolved_by: string | null;
            /** Onchain Tx Hash */
            onchain_tx_hash: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Resolved At */
            resolved_at: string | null;
        };
        /**
         * DisputeReason
         * @enum {string}
         */
        DisputeReason: "item_not_received" | "item_not_as_described" | "buyer_unresponsive" | "damaged_in_transit" | "other";
        /**
         * DisputeStatus
         * @enum {string}
         */
        DisputeStatus: "open" | "under_review" | "auto_resolved" | "arbitrated" | "closed";
        /** FraudLogRead */
        FraudLogRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Transaction Id
             * Format: uuid
             */
            transaction_id: string;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Fraud Probability */
            fraud_probability: string;
            /** Is Flagged */
            is_flagged: boolean;
            /** Risk Factors */
            risk_factors: {
                [key: string]: unknown;
            } | null;
            /** Reviewed By Admin Id */
            reviewed_by_admin_id: string | null;
            /** Admin Decision */
            admin_decision: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FraudReviewUpdate */
        FraudReviewUpdate: {
            /** Admin Decision */
            admin_decision: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string | null;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /** Is Verified */
            is_verified: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            buyer?: components["schemas"]["BuyerProfileRead"] | null;
            seller?: components["schemas"]["SellerProfileRead"] | null;
        };
        /** OnchainTrustRead */
        OnchainTrustRead: {
            /**
             * Seller Id
             * Format: uuid
             */
            seller_id: string;
            /** Wallet Address */
            wallet_address: string | null;
            /** Is Onchain Registered */
            is_onchain_registered: boolean;
            /** Onchain Score */
            onchain_score: number | null;
            /** Blockchain Enabled */
            blockchain_enabled: boolean;
        };
        /** OrderCreate */
        OrderCreate: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            payment_method: components["schemas"]["PaymentMethod"];
        };
        /** OrderRead */
        OrderRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Buyer Id
             * Format: uuid
             */
            buyer_id: string;
            /**
             * Seller Id
             * Format: uuid
             */
            seller_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Quantity */
            quantity: number;
            /** Amount */
            amount: string;
            status: components["schemas"]["OrderStatus"];
            /** Onchain Order Id */
            onchain_order_id: number | null;
            /** Escrow Tx Hash */
            escrow_tx_hash: string | null;
            /** Delivered At */
            delivered_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "created" | "confirmed" | "shipped" | "delivered" | "disputed" | "resolved" | "cancelled";
        /** OrderStatusUpdate */
        OrderStatusUpdate: {
            status: components["schemas"]["OrderStatus"];
        };
        /** OrderWithTransaction */
        OrderWithTransaction: {
            order: components["schemas"]["OrderRead"];
            transaction: components["schemas"]["TransactionRead"];
        };
        /** Page[AdminUserRead] */
        Page_AdminUserRead_: {
            /** Items */
            items: components["schemas"]["AdminUserRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[BlockchainHashRead] */
        Page_BlockchainHashRead_: {
            /** Items */
            items: components["schemas"]["BlockchainHashRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[DisputeRead] */
        Page_DisputeRead_: {
            /** Items */
            items: components["schemas"]["DisputeRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[FraudLogRead] */
        Page_FraudLogRead_: {
            /** Items */
            items: components["schemas"]["FraudLogRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[OrderRead] */
        Page_OrderRead_: {
            /** Items */
            items: components["schemas"]["OrderRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[ProductRead] */
        Page_ProductRead_: {
            /** Items */
            items: components["schemas"]["ProductRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[TrustScoreRead] */
        Page_TrustScoreRead_: {
            /** Items */
            items: components["schemas"]["TrustScoreRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "upi" | "card" | "cod" | "wallet";
        /** ProductCreate */
        ProductCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Category */
            category: string;
            /** Tags */
            tags?: string[];
            /** Price */
            price: number | string;
            /**
             * Stock Quantity
             * @default 0
             */
            stock_quantity: number;
            /** Image Url */
            image_url?: string | null;
        };
        /** ProductRead */
        ProductRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Seller Id
             * Format: uuid
             */
            seller_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Category */
            category: string;
            /** Tags */
            tags: string[];
            /** Price */
            price: string;
            /** Stock Quantity */
            stock_quantity: number;
            /** Image Url */
            image_url: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProductUpdate */
        ProductUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Price */
            price?: number | string | null;
            /** Stock Quantity */
            stock_quantity?: number | null;
            /** Image Url */
            image_url?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * ProfileUpdate
         * @description Fields only apply to the caller's own role; irrelevant ones (e.g. a
         *     buyer sending business_name) are silently ignored rather than erroring
         *     — same "own profile, partial update" contract as PATCH /products/{id}.
         */
        ProfileUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Wallet Address */
            wallet_address?: string | null;
            /** City */
            city?: string | null;
            /** Preferred Categories */
            preferred_categories?: string[] | null;
            /** Business Name */
            business_name?: string | null;
            /** Gstin */
            gstin?: string | null;
            /** Delivery Radius Km */
            delivery_radius_km?: number | null;
        };
        /** RecommendationItemRead */
        RecommendationItemRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            product: components["schemas"]["ProductRead"];
            /** Algorithm */
            algorithm: string;
            /** Score */
            score: string;
            /** Rank */
            rank: number;
            /** Was Clicked */
            was_clicked: boolean;
            /** Was Purchased */
            was_purchased: boolean;
            /**
             * Shown At
             * Format: date-time
             */
            shown_at: string;
            /** Distance Km */
            distance_km?: number | null;
            /** Estimated Delivery Days */
            estimated_delivery_days?: number | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ReturnRequest */
        ReturnRequest: {
            reason: components["schemas"]["DisputeReason"];
            /** Description */
            description?: string | null;
            /**
             * Item Condition
             * @default good
             */
            item_condition: string;
        };
        /** ReviewCreate */
        ReviewCreate: {
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /** Rating */
            rating: number;
            /** Comment */
            comment?: string | null;
        };
        /** ReviewRead */
        ReviewRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /**
             * Buyer Id
             * Format: uuid
             */
            buyer_id: string;
            /**
             * Seller Id
             * Format: uuid
             */
            seller_id: string;
            /** Rating */
            rating: number;
            /** Comment */
            comment: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SellerProfileRead */
        SellerProfileRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Business Name */
            business_name: string;
            /** Wallet Address */
            wallet_address: string | null;
            /** Gstin */
            gstin: string | null;
            /** City */
            city: string | null;
            /** Delivery Radius Km */
            delivery_radius_km: number;
            /** Seller Age Days */
            seller_age_days: number;
            /** Current Trust Score */
            current_trust_score: string;
            /** Is Onchain Registered */
            is_onchain_registered: boolean;
        };
        /** SellerRegisterRequest */
        SellerRegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone?: string | null;
            /** Business Name */
            business_name: string;
            /** Gstin */
            gstin?: string | null;
            /** City */
            city?: string | null;
            /**
             * Delivery Radius Km
             * @default 50
             */
            delivery_radius_km: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            role: components["schemas"]["UserRole"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** TransactionRead */
        TransactionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /**
             * Buyer Id
             * Format: uuid
             */
            buyer_id: string;
            /**
             * Seller Id
             * Format: uuid
             */
            seller_id: string;
            /** Amount */
            amount: string;
            payment_method: components["schemas"]["PaymentMethod"];
            status: components["schemas"]["TransactionStatus"];
            /** Is Fraud Flagged */
            is_fraud_flagged: boolean;
            /** Fraud Probability */
            fraud_probability: string | null;
            /** Onchain Tx Hash */
            onchain_tx_hash: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TransactionStatus
         * @enum {string}
         */
        TransactionStatus: "pending" | "success" | "failed" | "refunded";
        /** TrustScoreRead */
        TrustScoreRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Seller Id
             * Format: uuid
             */
            seller_id: string;
            /** Score */
            score: string;
            /** Transaction Success Rate */
            transaction_success_rate: string | null;
            /** Delivery Success Rate */
            delivery_success_rate: string | null;
            /** Avg Customer Rating */
            avg_customer_rating: string | null;
            /** Complaint Ratio */
            complaint_ratio: string | null;
            /** Dispute Count */
            dispute_count: number;
            /** Fraud Probability */
            fraud_probability: string | null;
            /** Refund Ratio */
            refund_ratio: string | null;
            /** Late Delivery Ratio */
            late_delivery_ratio: string | null;
            /** Order Completion Rate */
            order_completion_rate: string | null;
            /** Onchain Tx Hash */
            onchain_tx_hash: string | null;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "buyer" | "seller" | "admin";
        /** UserStatusUpdate */
        UserStatusUpdate: {
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WishlistItemCreate */
        WishlistItemCreate: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
        };
        /** WishlistItemRead */
        WishlistItemRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            product: components["schemas"]["ProductRead"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_buyer_api_v1_auth_register_buyer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyerRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_seller_api_v1_auth_register_seller_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SellerRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_access_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    update_me_api_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_v1_products_get: {
        parameters: {
            query?: {
                category?: string | null;
                seller_id?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProductRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_v1_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_products_api_v1_products_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"][];
                };
            };
        };
    };
    get_product_api_v1_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_product_api_v1_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_v1_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_v1_orders_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OrderRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_api_v1_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderWithTransaction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_v1_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_order_transactions_api_v1_orders__order_id__transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_order_status_api_v1_orders__order_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_return_api_v1_orders__order_id__return_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReturnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fraud_alerts_api_v1_fraud_alerts_get: {
        parameters: {
            query?: {
                only_flagged?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FraudLogRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_fraud_log_api_v1_fraud_logs__fraud_log_id__review_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fraud_log_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FraudReviewUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FraudLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_trust_score_api_v1_trust_sellers__seller_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seller_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustScoreRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trust_score_history_api_v1_trust_sellers__seller_id__history_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                seller_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TrustScoreRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_recompute_api_v1_trust_sellers__seller_id__recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seller_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustScoreRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_onchain_trust_api_v1_trust_sellers__seller_id__onchain_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seller_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnchainTrustRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_api_v1_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_seller_reviews_api_v1_reviews_sellers__seller_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seller_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recommendations_api_v1_recommendations_get: {
        parameters: {
            query?: {
                top_k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_click_api_v1_recommendations__recommendation_id__click_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ctr_report_api_v1_recommendations_ctr_get: {
        parameters: {
            query?: {
                algorithm?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CTRReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_disputes_api_v1_disputes_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DisputeRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    raise_dispute_api_v1_disputes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_evidence_api_v1_disputes__dispute_id__evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispute_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeEvidenceSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    arbitrate_dispute_api_v1_disputes__dispute_id__arbitrate_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispute_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeArbitrate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dispute_api_v1_disputes__dispute_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispute_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisputeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_wishlist_api_v1_wishlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemRead"][];
                };
            };
        };
    };
    add_to_wishlist_api_v1_wishlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishlistItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_wishlist_api_v1_wishlist__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                role?: components["schemas"]["UserRole"] | null;
                is_active?: boolean | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AdminUserRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_status_api_v1_admin_users__user_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_api_v1_admin_analytics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsReport"];
                };
            };
        };
    };
    list_blockchain_hashes_api_v1_admin_blockchain_hashes_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BlockchainHashRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
