"""initial schema

Hand-written (not autogenerated) to mirror database/schema.sql exactly,
column for column — that file is the documented source of truth for the
relational model; this migration is how it actually gets applied to
Postgres. If you change one, change both (see the header comment in
schema.sql).

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-04
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

UUID_DEFAULT = sa.text("gen_random_uuid()")


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    user_role = postgresql.ENUM("buyer", "seller", "admin", name="user_role")
    order_status = postgresql.ENUM(
        "created", "confirmed", "shipped", "delivered", "disputed", "resolved", "cancelled",
        name="order_status",
    )
    payment_method = postgresql.ENUM("upi", "card", "cod", "wallet", name="payment_method")
    transaction_status = postgresql.ENUM("pending", "success", "failed", "refunded", name="transaction_status")
    dispute_status = postgresql.ENUM(
        "open", "under_review", "auto_resolved", "arbitrated", "closed", name="dispute_status"
    )
    dispute_reason = postgresql.ENUM(
        "item_not_received", "item_not_as_described", "buyer_unresponsive", "damaged_in_transit", "other",
        name="dispute_reason",
    )

    # ---- users ----------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("full_name", sa.String(255), nullable=False),
        sa.Column("phone", sa.String(20)),
        sa.Column("role", user_role, nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("is_verified", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("last_login_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("idx_users_email", "users", ["email"])
    op.create_index("idx_users_role", "users", ["role"])

    # ---- buyers -----------------------------------------------------------
    op.create_table(
        "buyers",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column(
            "user_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True,
        ),
        sa.Column("wallet_address", sa.String(42)),
        sa.Column(
            "price_sensitivity", sa.Numeric(3, 2), nullable=False, server_default="0.5",
        ),
        sa.Column("preferred_categories", postgresql.ARRAY(sa.Text), nullable=False, server_default="{}"),
        sa.Column("account_age_days", sa.Integer, nullable=False, server_default="0"),
        sa.Column("is_flagged_fraud", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("price_sensitivity BETWEEN 0 AND 1", name="ck_buyers_price_sensitivity"),
    )
    op.create_index("idx_buyers_wallet", "buyers", ["wallet_address"])

    # ---- sellers ------------------------------------------------------------
    op.create_table(
        "sellers",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column(
            "user_id", postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True,
        ),
        sa.Column("business_name", sa.String(255), nullable=False),
        sa.Column("wallet_address", sa.String(42)),
        sa.Column("gstin", sa.String(15)),
        sa.Column("seller_age_days", sa.Integer, nullable=False, server_default="0"),
        sa.Column("current_trust_score", sa.Numeric(5, 2), nullable=False, server_default="50.00"),
        sa.Column("is_onchain_registered", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("is_flagged_fraud", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("idx_sellers_wallet", "sellers", ["wallet_address"])
    op.create_index("idx_sellers_trust_score", "sellers", ["current_trust_score"])

    # ---- products -----------------------------------------------------------
    op.create_table(
        "products",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column("seller_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("sellers.id", ondelete="CASCADE"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text),
        sa.Column("category", sa.String(100), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.Text), nullable=False, server_default="{}"),
        sa.Column("price", sa.Numeric(10, 2), nullable=False),
        sa.Column("stock_quantity", sa.Integer, nullable=False, server_default="0"),
        sa.Column("image_url", sa.Text),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("price >= 0", name="ck_products_price"),
        sa.CheckConstraint("stock_quantity >= 0", name="ck_products_stock_quantity"),
    )
    op.create_index("idx_products_seller", "products", ["seller_id"])
    op.create_index("idx_products_category", "products", ["category"])
    op.create_index("idx_products_active", "products", ["is_active"])

    # ---- orders -------------------------------------------------------------
    op.create_table(
        "orders",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column("buyer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("buyers.id"), nullable=False),
        sa.Column("seller_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("sellers.id"), nullable=False),
        sa.Column("product_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("products.id"), nullable=False),
        sa.Column("quantity", sa.Integer, nullable=False, server_default="1"),
        sa.Column("amount", sa.Numeric(10, 2), nullable=False),
        sa.Column("status", order_status, nullable=False, server_default="created"),
        sa.Column("onchain_order_id", sa.BigInteger),
        sa.Column("escrow_tx_hash", sa.String(66)),
        sa.Column("delivered_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("quantity > 0", name="ck_orders_quantity"),
        sa.CheckConstraint("amount >= 0", name="ck_orders_amount"),
    )
    op.create_index("idx_orders_buyer", "orders", ["buyer_id"])
    op.create_index("idx_orders_seller", "orders", ["seller_id"])
    op.create_index("idx_orders_status", "orders", ["status"])

    # ---- transactions -------------------------------------------------------
    op.create_table(
        "transactions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column("order_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("orders.id", ondelete="CASCADE"), nullable=False),
        sa.Column("buyer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("buyers.id"), nullable=False),
        sa.Column("seller_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("sellers.id"), nullable=False),
        sa.Column("amount", sa.Numeric(10, 2), nullable=False),
        sa.Column("payment_method", payment_method, nullable=False),
        sa.Column("status", transaction_status, nullable=False, server_default="pending"),
        sa.Column("is_fraud_flagged", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("fraud_probability", sa.Numeric(5, 4)),
        sa.Column("onchain_tx_hash", sa.String(66)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("idx_transactions_order", "transactions", ["order_id"])
    op.create_index("idx_transactions_buyer", "transactions", ["buyer_id"])
    op.create_index("idx_transactions_seller", "transactions", ["seller_id"])
    op.create_index("idx_transactions_fraud_flagged", "transactions", ["is_fraud_flagged"])

    # ---- blockchain_hashes ----------------------------------------------------
    op.create_table(
        "blockchain_hashes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column("entity_type", sa.String(50), nullable=False),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("tx_hash", sa.String(66), nullable=False),
        sa.Column("block_number", sa.BigInteger),
        sa.Column("network", sa.String(50), nullable=False, server_default="sepolia"),
        sa.Column("event_type", sa.String(100), nullable=False),
        sa.Column("payload_hash", sa.String(66)),
        sa.Column("confirmed_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("idx_blockchain_hashes_entity", "blockchain_hashes", ["entity_type", "entity_id"])
    op.create_index("idx_blockchain_hashes_tx", "blockchain_hashes", ["tx_hash"])

    # ---- trust_scores -----------------------------------------------------
    op.create_table(
        "trust_scores",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column("seller_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("sellers.id", ondelete="CASCADE"), nullable=False),
        sa.Column("score", sa.Numeric(5, 2), nullable=False),
        sa.Column("transaction_success_rate", sa.Numeric(5, 4)),
        sa.Column("delivery_success_rate", sa.Numeric(5, 4)),
        sa.Column("avg_customer_rating", sa.Numeric(3, 2)),
        sa.Column("complaint_ratio", sa.Numeric(5, 4)),
        sa.Column("dispute_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("fraud_probability", sa.Numeric(5, 4)),
        sa.Column("refund_ratio", sa.Numeric(5, 4)),
        sa.Column("late_delivery_ratio", sa.Numeric(5, 4)),
        sa.Column("order_completion_rate", sa.Numeric(5, 4)),
        sa.Column("onchain_tx_hash", sa.String(66)),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name="ck_trust_scores_score"),
    )
    op.create_index("idx_trust_scores_seller", "trust_scores", ["seller_id"])
    op.create_index("idx_trust_scores_computed_at", "trust_scores", ["computed_at"])

    # ---- disputes -----------------------------------------------------------
    op.create_table(
        "disputes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column("order_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("orders.id", ondelete="CASCADE"), nullable=False),
        sa.Column("raised_by_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("reason", dispute_reason, nullable=False),
        sa.Column("description", sa.Text),
        sa.Column("evidence_buyer_score", sa.Numeric(3, 2), server_default="0"),
        sa.Column("evidence_seller_score", sa.Numeric(3, 2), server_default="0"),
        sa.Column("status", dispute_status, nullable=False, server_default="open"),
        sa.Column("resolution_outcome", sa.String(100)),
        sa.Column("seller_share_bps", sa.Integer),
        sa.Column("resolved_by", sa.String(20)),
        sa.Column("onchain_tx_hash", sa.String(66)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("resolved_at", sa.DateTime(timezone=True)),
        sa.CheckConstraint("seller_share_bps BETWEEN 0 AND 10000", name="ck_disputes_seller_share_bps"),
    )
    op.create_index("idx_disputes_order", "disputes", ["order_id"])
    op.create_index("idx_disputes_status", "disputes", ["status"])

    # ---- recommendations ------------------------------------------------------
    op.create_table(
        "recommendations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column("buyer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("buyers.id", ondelete="CASCADE"), nullable=False),
        sa.Column("product_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("products.id", ondelete="CASCADE"), nullable=False),
        sa.Column("algorithm", sa.String(50), nullable=False),
        sa.Column("score", sa.Numeric(6, 5), nullable=False),
        sa.Column("rank", sa.Integer, nullable=False),
        sa.Column("was_clicked", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("was_purchased", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("shown_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("clicked_at", sa.DateTime(timezone=True)),
    )
    op.create_index("idx_recommendations_buyer", "recommendations", ["buyer_id"])
    op.create_index("idx_recommendations_product", "recommendations", ["product_id"])

    # ---- fraud_logs -----------------------------------------------------------
    op.create_table(
        "fraud_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column("transaction_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("transactions.id", ondelete="CASCADE"), nullable=False),
        sa.Column("model_name", sa.String(50), nullable=False),
        sa.Column("model_version", sa.String(20), nullable=False),
        sa.Column("fraud_probability", sa.Numeric(5, 4), nullable=False),
        sa.Column("is_flagged", sa.Boolean, nullable=False),
        sa.Column("risk_factors", postgresql.JSONB),
        sa.Column("reviewed_by_admin_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id")),
        sa.Column("admin_decision", sa.String(20)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("idx_fraud_logs_transaction", "fraud_logs", ["transaction_id"])
    op.create_index("idx_fraud_logs_flagged", "fraud_logs", ["is_flagged"])

    # ---- reviews --------------------------------------------------------------
    op.create_table(
        "reviews",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column("order_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("orders.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("buyer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("buyers.id"), nullable=False),
        sa.Column("seller_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("sellers.id"), nullable=False),
        sa.Column("rating", sa.SmallInteger, nullable=False),
        sa.Column("comment", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="ck_reviews_rating"),
    )
    op.create_index("idx_reviews_seller", "reviews", ["seller_id"])


def downgrade() -> None:
    for table in (
        "reviews", "fraud_logs", "recommendations", "disputes", "trust_scores",
        "blockchain_hashes", "transactions", "orders", "products", "sellers",
        "buyers", "users",
    ):
        op.drop_table(table)

    for enum_name in (
        "dispute_reason", "dispute_status", "transaction_status", "payment_method",
        "order_status", "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
